#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <climits>
#include <cfloat>
#include <cctype>
#include <cassert>
#include <limits>
#include <bitset>
#include <complex>
#include <queue>
#include <stack>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <streambuf>
#include <istream>
#include <ostream>